<a href="https://colab.research.google.com/github/Rvkt/Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

# **Lists**

In [2]:
mylist = [1, 2, 3, 4, 5]
print(mylist)

[1, 2, 3, 4, 5]


**Numpy Array**

In [13]:
np1 = np.random.rand(3,4)
np1

array([[0.63121427, 0.72083987, 0.948424  , 0.43668202],
       [0.13723986, 0.33254896, 0.24707935, 0.10603837],
       [0.6105789 , 0.85440225, 0.77667428, 0.29169955]])

In [14]:
np1.dtype

dtype('float64')

# **TENSORS**

In [16]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.7599, -1.3845,  1.7191,  0.8262],
        [-0.6713,  0.7984,  0.6818,  0.6106],
        [ 2.3199, -0.0102, -0.0864,  0.6259]])

In [15]:
tensor_2d.dtype

torch.float32

In [17]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6312, 0.7208, 0.9484, 0.4367],
        [0.1372, 0.3325, 0.2471, 0.1060],
        [0.6106, 0.8544, 0.7767, 0.2917]], dtype=torch.float64)